# Generated by Django 3.2.11 on 2022-02-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('data', models.TextField(blank=True, max_length=16383)),
                ('date_time_created', models.CharField(max_length=64)),
                ('date_deleted', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('data', models.TextField(blank=True, max_length=16383)),
                ('date_time_created', models.CharField(max_length=64)),
            ],
        ),
    ]
