# Generated by Django 3.2.11 on 2022-02-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bit95', '0001_initial'),
    ]

    operations = [
    ]
