# Generated by Django 3.2.11 on 2022-02-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bit95', '0011_auto_20220201_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_files',
            name='data',
            field=models.TextField(blank=True, max_length=16383),
        ),
        migrations.AlterField(
            model_name='files',
            name='data',
            field=models.TextField(blank=True, max_length=16383),
        ),
    ]
