# Generated by Django 3.2.11 on 2022-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bit95', '0012_auto_20220201_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_files',
            name='date_deleted',
            field=models.CharField(default='02 Feb', max_length=64),
        ),
        migrations.AlterField(
            model_name='files',
            name='data',
            field=models.TextField(blank=True, default='02 Feb', max_length=16383),
        ),
    ]
