# Generated by Django 3.2.11 on 2022-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bit95', '0013_auto_20220202_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='data',
            field=models.TextField(blank=True, max_length=16383),
        ),
        migrations.AlterField(
            model_name='files',
            name='date_time_created',
            field=models.CharField(default='02 Feb', max_length=64),
        ),
    ]
