# Generated by Django 3.2.11 on 2022-02-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bit95', '0016_auto_20220202_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_files',
            name='type',
            field=models.CharField(default='Text Document', max_length=32),
        ),
        migrations.AlterField(
            model_name='files',
            name='type',
            field=models.CharField(default='Text Document', max_length=32),
        ),
    ]
